### ISSUE TITLE
gridFS access from mongolite?

### ISSUE THREAD

**Issue by leifwenn** [jeroen/mongolite#40]
we'd like to use the mongodb gridFS system to work with large files. I do not see a way to do that now. Is it feasible to expand mongolite to provide this?

**Comment by fred777** [comment]
Until gridFS is supported by mongolite, which may be never, try https://github.com/dselivanov/rmongodb 

It's outdated / not really maintained anymore, but gridFS access absolutely works (I committed a gridfs-patch a while ago)...

**Comment by leifwenn** [comment]
thanks fred777. we have had trouble simultaneously loading mongolite and rmongodb--couldn't  connect with one and switch to connecting with the other. rmongodb is sometimes comparatively very slow, but it is what we'll use till the day mongolite has gridFS.

**Comment by jeroenooms** [comment]
I'm trying to find some resources to work on mongolite soon. But if you contribute a PR that would help too. http://mongoc.org/libmongoc/current/mongoc_gridfs_t.html

**Comment by leifwenn** [comment]
I wish I could help, but the effort is currently beyond my skills and time allocation. I'll have to wait.

**Comment by jeroenooms** [comment]
@leifwenn @fred777 can you help me by explaining what you need from gridfs and how you would like to use this? I don't understand really what this does.

**Comment by fred777** [comment]
@jeroenooms: GridFS is an API by which you can use MongoDB as a simple key-value-store where the key is a string and the value is an arbitrary binary blob without any size limitation. Large blobs will be divided into 255kB chunks.

https://docs.mongodb.com/manual/core/gridfs/

**Comment by jeroenooms** [comment]
SO I guess this would best be a separate API object? It makes no sense in combination with the other API's? (find, aggregate, etc) does it?

**Comment by fred777** [comment]
Sort of... yes. We need a key-value-store-api, i.e. list all keys / find with regex as well as store / retrieve.

With the present API, it is already possible to browse GridFS via browsing the files-Collection (say "mykeyvaluestore.files"). But mind that directly accessing and modifying the files metadata collection with the current mongolite API may mess up GridFS.

In order to retrieve a binary blob, all related chunks from "mykeyvaluestore.chunks" have to be determined, retrieved and merged - and this is where some magic has to be implemented. The same is true for storing, But mongoc already has high-level helpers for this:

http://mongoc.org/libmongoc/1.4.0/mongoc_gridfs_t.html

**Comment by leifwenn** [comment]
We have been using rmongodb's gridfs tools to archive Excel files, as
follows:

mgrids = rmongodb::mongo.gridfs.create(db(ctxt), "clingen","fs")
rmongodb::mongo.gridfs.store.file(mgrids,file,basename(file))


where file is the full path to an xlsx file.

Hope this helps. If you need more let me know,
Leif

**Comment by FidelCastillo** [comment]
we have the gridFS in mongolite finally?? thanks for your work in that wonderfull tool

**Comment by jeroen** [comment]
This is still very experimental at this point. Everything is untested and subject to change.

**Comment by jeroen** [comment]
But if you want to help testing that would be great :)

**Comment by FidelCastillo** [comment]
sure...

**Comment by jeroen** [comment]
This is in master now. Please open new issues for specific bugs or feature requests.
