### ISSUE TITLE
Iterator API for aggregate/mapreduce

### ISSUE THREAD

**Issue by renkun-ken** [jeroen/mongolite#52]
It is nice to have `$iterate` to work with large documents with nested structures and preserve their structure as a `list` and fetch results chunk by chunk. 

Is it possible to also iterate over aggregation results so that I can preserve the `list` structure or fetch by chunk?

**Comment by crubb** [comment]
Hey,

I looked into this a little, since I needed it as well. Unfortunately, the `iterate()` options are geared towards `find()`. The functionality could be easily achieved by adding a new function in `R/mongo.R`, along the lines:

```
aggregate_iterate <- function(pipeline = '{}', options = '{"allowDiskUse":true}') {
  check_col()
  cur <- mongo_collection_aggregate(col, pipeline, options)
  # make sure 'col' does not go out of scope to prevent gc
  mongo_iterator(cur, col)
}
```

But this seems to differ a little from the (naming) philosophy of mongolite. Therefore I haven't submitted a PR. What do you think?

Best,
crubb

**Comment by crubb** [comment]
Hey,

I looked into this a little, since I needed it as well. Unfortunately, the `iterate()` options are geared towards `find()`. The functionality could be easily achieved by adding a new function in `R/mongo.R`, along the lines:

```
aggregate_iterate <- function(pipeline = '{}', options = '{"allowDiskUse":true}') {
  check_col()
  cur <- mongo_collection_aggregate(col, pipeline, options)
  # make sure 'col' does not go out of scope to prevent gc
  mongo_iterator(cur, col)
}
```

But this seems to differ a little from the (naming) philosophy of mongolite. Therefore I haven't submitted a PR. What do you think?

Best,
crubb

**Comment by jeroen** [comment]
I have added an `iterate` parameter to `aggregate()` to return the result as an iterator instead of data frame.

For map reduce however it is more complicated because as far as I can see, the results are always a single-row collection with a `results` property (so there is nothing to iterate). I think you are supposed to set `out` to a collection name, so that the results of the map/reduce get written to a collection. And then you can make a new connection to the output collection and iterate from that.

If anyone knows of a better solution, let me know.
