### ISSUE TITLE
Switching collection without creating new client?

### ISSUE THREAD

**Issue by jhan1** [jeroen/mongolite#84]
Is there any way we can switch collection without initiating new client/connection? I looked at your implementation and am thinking `mongo_collection_new(client, collection, db)` might do the job, but couldn't access `client` object from outside `mongo()` function. 

Thanks for a great package. Thoroughly enjoying it!

**Comment by jeroen** [comment]
Don't have that yet. Why would you need this? Wouldn't it be cleaner to start a new connection?

**Comment by bonartm** [comment]
In my understanding it would increase performance if a lot of collections will be used. Using only one connection for all collections should be much faster compared to open a connection for each collection.
 
E.g. I am using mongolite in a Shiny Web App to display data from dozens of collections in a mongo db. It takes always several seconds until the data is displayed because it takes so long to open all the collections. Or is there allready a better way to do it?

Example:

dbs <- lapply(collections, function(collection) 
    mongo(collection, db, uri))

Thank you for your work!

**Comment by mredaelli** [comment]
I forked the package here https://github.com/mredaelli/mongolite and added this feature in the ft-oneconnection branch. It's working for us (and indeed it is much faster), but this is my first time with R, C bindings, packaging etc, so I'd be happy for a second opinion :)

Basically the syntax is unchanged, and I added a function $use() to switch to another db/collection.

Happy to make a pull request, if @jeroen is interested.

**Comment by ramanan82** [comment]
I would like to have this feature, since I encounter the following scenario often: My shiny app needs to access a persistent connection object defined at the top level (before runApp), so that 100 new connections are not made when 100 different customers start a session. I would not only need to change the collection name, but also the database name of the connection depending upon the session parameters (jobId, customerId etc.)

With Pymongo this is no problem since there is a 'client'-level object available that uses only one connection no matter how many different databases/collections are queried with it. Would like @jeroen to consider this.

**Comment by mredaelli** [comment]
I finally understood (I think) a bit more of R package development, checks etc, and I think the PR makes now more sense.
@jeroen , the only errors seem to be coming from warning for compilation flags. Can you let me know if more changes are needed?

**Comment by jeroen** [comment]
The latest version of mongolite introduces automatic connection pooling. So when you create multiple collection or gridfs objects to the same server, it will use the use a single connnection.
